credentials:
  usernames:
    bbgwiki:
      email: bbglab@irbbarcelona.org
      name: bbgwiki
      password: $2b$12$vK609AhQOIzoqmS4xMZXUOu2dO1Jl7DskL0Me0HtNMvBGgRqfMCry # pass_bbgwiki

cookie:
  expiry_days: 1
  key: 4b2b77b2eb868033eb5fc273e0c74a8e
  name: bbgwiki_user_auth

example_queries:
  - "What is the bbgwiki?"
  - "How can I edit the bbgwiki?"
  - "What is the St. Jude dataset?"
  - "Show me the code to compute the type of variant"
  - "How does the coffee machine system work?"
  - "Show me the code to obtain the correct order of the 96 trinucleotide context"